apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 100.0.0
directories:
- path: vendor
  contents:
  - path: github.com/cloudfoundry/cf-k8s-networking
    git:
      url: https://github.com/cloudfoundry/cf-k8s-networking
      ref: 2b009b61fa8afb330a4302c694ee61b11104c54c
    includePaths:
    - cfroutesync/crds/**/*
    - install/ytt/networking/**/*
