apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  ## Default repository has been deprecated
  # - path: default-repo
  #   helmChart:
  #     name: stable/redis

  - path: custom-repo-custom-version
    helmChart:
      name: contour
      version: "7.10.0"
      repository:
        url: https://charts.bitnami.com/bitnami
